spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/proposaldb
    username: joel
    password: postgres123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    locations: classpath:db/migration, classpath:db/testdb
    baselineOnMigrate: true
